### PR TITLE
add @alexandratran as a maintainer

### PR DESCRIPTION
**Pull request by NicolasMassart**
## PR description

This is a proposal to add Alexandra Tran as a maintainer.

### Disclosure

Alexandra is part of Consensys Protocol doc team.

### Process

Change will be accepted if the following rules are followed:

- [x] 5 significant changes have been authored by the proposed maintainer and accepted.
  Here is [the list of changes Alexandra recently made](https://github.com/hyperledger/besu-docs/pulls?q=is%3Apr+is%3Amerged+author%3Aalexandratran).
- [x] The proposed maintainer has the sponsorship of at least one other maintainer.
    - [x] This sponsoring maintainer will create a PR modifying the list of maintainers. **-> that's me**
    - [x] The proposed maintainer accepts the nomination and expresses a willingness to be a long-term (more than 6 months) committer.
    - [x] This would be a comment in the above PR. **@alexandratran can you comment on this PR to accept please?**
- [x] This PR will be communicated in all appropriate communication channels.
      It should be mentioned in any maintainer/community call.
      It should also be posted to the appropriate mailing list or chat channels if they exist.
      **See Hyperledger [RocketChat](https://chat.hyperledger.org/channel/besu-contributors) and [mailing list](https://lists.hyperledger.org/g/besu)**
- [x] Approval by at least 3 current maintainers within two weeks **(until 2021, April 2nd)** of the proposal,
- [ ] or an absolute majority of current maintainers.
    - These votes will be recorded as review approval, comments or 👍 in the PR modifying the list of maintainers.
- [ ] No veto by another maintainer within two weeks of proposal are recorded **(until 2021, April 2nd)**.
    - All vetoes must be accompanied by a public explanation as a comment in the PR for adding this maintainer
    - The explanation of the veto must be reasonable.
    - A veto can be retracted, in that case the approval/veto timeframe is reset.
    - It is bad form to veto, retract, and veto again.
- The proposed maintainer becomes a maintainer
    - Either two weeks have passed since the third approval **(on 2021, April 2nd)**,
    - Or an absolute majority of maintainers approve.
    - In either case, no maintainer presents a veto.

## Maintainers able to vote on this

All users in https://github.com/orgs/hyperledger/teams/besu-docs-maintainers/members and https://github.com/orgs/hyperledger/teams/besu-maintainers/members

Total is 25 unique users => absolute majority is 13 users.

### CODE REVIEW

**Review by timbeiko — APPROVED** [review]

**Review by RatanRSur — APPROVED** [review]

**Comment by NicolasMassart** [comment]
We reached the 3 maintainers approval already. @MadelineMurray @timbeiko and myself.

**Comment by alexandratran** [comment]
I accept the nomination to become a long-term Besu doc maintainer.

**Review by pinges — APPROVED** [review]

**Review by shemnon — APPROVED** [review]

**Review by bgravenorst — APPROVED** [review]

**Review by macfarla — APPROVED** [review]
LGTM

**Review by lucassaldanha — APPROVED** [review]

**Comment by NicolasMassart** [comment]
9 approvals so far

**Review by usmansaleem — APPROVED** [review]
👍

**Review by atoulme — APPROVED** [review]

**Comment by NicolasMassart** [comment]
All the conditions are met so @alexandratran can now be added in @hyperledger/besu-docs-maintainers

**Pull request merged**
