### PR TITLE
Add Grant as a maintainer

### LINKED ISSUE #198: Propose Grant Noble as maintainer and move Steven to emeritus

### PR DESCRIPTION
**Pull request by NicolasMassart**
## PR description
This is a proposal to add Grant as a maintainer.

**Disclosure**: Grant is part of Consensys Pegasys doc team now.

**REMINDER**: change will be accepted if the following rules are followed:

- ✅5 significant changes have been authored by the proposed maintainer and
  accepted. Here is [the list of changes Grant recently made](https://github.com/hyperledger/besu-docs/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+author%3Agrantnoble).
- ✅The proposed maintainer has the sponsorship of at least one other maintainer.
  -  ✅ This sponsoring maintainer will create a PR modifying the list of
    maintainers. **-> that's me**
  - ✅ The proposed maintainer accepts the nomination and expresses a willingness
    to be a long-term (more than 6 months) committer.
  - ✅ This would be a comment in the above PR. **@grantnoble can you comment on this PR to accept please?**
  -  ✅This PR will be communicated in all appropriate communication channels. It
    should be mentioned in any maintainer/community call. It should also be
    posted to the appropriate mailing list or chat channels if they exist. **See Hyperledger chat and mailing list**
- ✅Approval by at least 3 current maintainers within two weeks **(until March 9th)** of the proposal or
  ✅an absolute majority of current maintainers.
  - These votes will be recorded in the PR modifying the list of maintainers.
-  No veto by another maintainer within two weeks of proposal are recorded **(until March 9th)**.
  - All vetoes must be accompanied by a public explanation as a comment in the
    PR for adding this maintainer
  - The explanation of the veto must be reasonable.
  - A veto can be retracted, in that case the approval/veto timeframe is reset.
  - It is bad form to veto, retract, and veto again.
- The proposed maintainer becomes a maintainer
  - Either two weeks have passed since the third approval **(on March 9th)**,
  - Or an absolute majority of maintainers approve.
  - In either case, no maintainer presents a veto.

## Fixed Issue(s)
#198

### CODE REVIEW

**Comment by grantnoble** [comment]
I accept the nomination to be a long-term maintainer and committer.

**Comment by ajsutton** [comment]
The title of this PR is to add Grant, but the changes also move Steven Gregg into emeritus.  That should be a separate issue, with its own clear notifications to the Besu mailing list and rocket chat.

**Comment by MadelineMurray** [comment]
LGTM

**Comment by NicolasMassart** [comment]
Absolute majority was reached on this PR (3 on 4) so we can merge this without further waiting.

**Pull request merged**
