### PR TITLE
add @rolandtyler as maintainer

### PR DESCRIPTION
**Pull request by alexandratran**
## PR description

This is a proposal to add Roland Tyler (@rolandtyler) as a maintainer.

### Disclosure

Roland is part of Consensys Protocol doc team.

### Process

Change will be accepted if the following rules are followed:

- [x] 5 significant changes have been authored by the proposed maintainer and accepted.
  Here is [the list of changes Roland recently made](https://github.com/hyperledger/besu-docs/pulls?q=is%3Apr+is%3Amerged+author%3Arolandtyler).
- [x] The proposed maintainer has the sponsorship of at least one other maintainer.
    - [x] This sponsoring maintainer will create a PR modifying the list of maintainers. **-> that's me**
    - [x] The proposed maintainer accepts the nomination and expresses a willingness to be a long-term (more than 6 months) committer.
    - [x] This would be a comment in the above PR. **@rolandtyler can you comment on this PR to accept please?**
- [x] This PR will be communicated in all appropriate communication channels.
      It should be mentioned in any maintainer/community call.
      It should also be posted to the appropriate mailing list or chat channels if they exist.
      **See Hyperledger [RocketChat](https://chat.hyperledger.org/channel/besu-contributors) and [mailing list](https://lists.hyperledger.org/g/besu)**
- [x] Approval by at least 3 current maintainers within two weeks **(until 2021, September 17)** of the proposal,
- [ ] or an absolute majority of current maintainers.
    - These votes will be recorded as review approval, comments or 👍 in the PR modifying the list of maintainers.
- [ ] No veto by another maintainer within two weeks of proposal are recorded **(until 2021, September 17)**.
    - All vetoes must be accompanied by a public explanation as a comment in the PR for adding this maintainer
    - The explanation of the veto must be reasonable.
    - A veto can be retracted, in that case the approval/veto timeframe is reset.
    - It is bad form to veto, retract, and veto again.
- The proposed maintainer becomes a maintainer
    - Either two weeks have passed since the third approval **(on 2021, September 17)**,
    - Or an absolute majority of maintainers approve.
    - In either case, no maintainer presents a veto.

## Maintainers able to vote on this

All users in https://github.com/orgs/hyperledger/teams/besu-docs-maintainers/members and https://github.com/orgs/hyperledger/teams/besu-maintainers/members

Total is 28 unique users => absolute majority is 15 users.

### CODE REVIEW

**Comment by rolandtyler** [comment]
I accept the nomination and am willing to be a long term maintainer.

**Review by NicolasMassart — APPROVED** [review]

**Review by vmichalik — APPROVED** [review]

**Comment by alexandratran** [comment]
Three approvals reached (Nico, Vijay, and myself).

**Review by bgravenorst — APPROVED** [review]
Approved :)

**Review by atoulme — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
LGTM

**Review by macfarla — APPROVED** [review]

**Review by MadelineMurray — APPROVED** [review]

**Review by antonydenyer — APPROVED** [review]

**Review by sajz — APPROVED** [review]
lgtm

**Comment by NicolasMassart** [comment]
Made this PR a draft to make sure we do not merge if by accident.

**Review by jflo — APPROVED** [review]

**Review by garyschulte — APPROVED** [review]
👍

**Review by matkt — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Pull request merged**
