### PR TITLE
adding in tx tutorials

### PR DESCRIPTION
**Pull request by joshuafernandes**
Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [x] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

### For content changes

- [x] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

### CODE REVIEW

**Review by alexandratran — COMMENTED** [review]
Thanks for the content! I edited these but it will need some more eyes.

**Comment by bgravenorst** [comment]
Made some additional changes. @NicolasMassart, would you mind having a look at this one? Some strange Vale failures.

**Review by NicolasMassart — COMMENTED** [review]
Added some comments and fixed the Vale issue (it was just an extra space)

**Comment by joshuafernandes** [comment]
> Thanks for the content! I edited these but it will need some more eyes.

Thank you for reviewing :)

**Comment by joshuafernandes** [comment]
> Added some comments and fixed the Vale issue (it was just an extra space)

Thankyou Nico :)

**Review by alexandratran — APPROVED** [review]

**Comment by alexandratran** [comment]
Feel free to merge now @joshuafernandes :)

**Comment by joshuafernandes** [comment]
> Feel free to merge now @joshuafernandes :)

Thankyou @alexandratran :)

**Pull request merged**
