### PR TITLE
Updated brew install instructions per user feedback

### PR DESCRIPTION
**Pull request by MadelineMurray**
Updated brew install instructions per user feedback in issue #206

### CODE REVIEW

**Comment by ajsutton** [comment]
With the 1.4 release we've removed the old PegaSysEng/pantheon/brew tap and migrated it over to point to hyperledger/besu so I don't this this change is required anymore.  Probably doesn't hurt though.

Would be really useful to include a summary of the user feedback in the PR description for historical reference as well.

**Comment by MadelineMurray** [comment]
@ajsutton - ironic timing in that case.  Linked the issue with the feedback.

**Comment by ajsutton** [comment]
Yep so reviewing that feedback it should rapidly become a non-issue which is nice.

**Comment by MadelineMurray** [comment]
@ajsutton - given it'll become a non-issue I'm inclined to not merge this one.  `brew install besu` is easier than `brew install hyperledger/besu/besu`. WDYT?

**Comment by ajsutton** [comment]
I think the safe thing is to merge it. I think it happens when you have two taps that both provide besu.  That used to be PegaSysEng/pantheon (which provided a besu as part of the migration process that installed the same thing as hyperledger/besu).  But it could potentially be any tap the user added.

And I can't reproduce the original situation now so it's kind of hard to know for sure what situations someone's brew could wind up in depending on when they added and updated what.

So probably merge it anyway I guess...

**Comment by MadelineMurray** [comment]
Thanks - makes sense given we can't control which besu taps might be added in future.

**Pull request merged**
