### PR TITLE
Correct use of contractConstructorInit

### PR DESCRIPTION
**Pull request by stephenhodgkiss**

### CODE REVIEW

**Review by alexandratran — COMMENTED** [review]
Can you make this change to the latest version of the docs in the `/docs` folder?

**Comment by stephenhodgkiss** [comment]
> Can you make this change to the latest version of the docs in the `/docs` folder?

ok done

**Comment by stephenhodgkiss** [comment]
> Can you make this change to the latest version of the docs in the `/docs` folder?

Was that addressed to me or the reviewers?

**Comment by stephenhodgkiss** [comment]
Created new pull request, amending the file inside the /docs folder instead as requested @alexandratran 

See https://github.com/hyperledger/besu-docs/pull/1422

**Comment by stephenhodgkiss** [comment]
thx

**Pull request closed without merging**
