### PR TITLE
doc revert reason in eth_estimateGas error

### LINKED ISSUE #580: Update revert reason doc to indicate revert reason included with eth_estimate gas call errror
Dev PR: https://github.com/hyperledger/besu/pull/1730

### PR DESCRIPTION
**Pull request by alexandratran**
## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [x] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [x] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [x] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [x] you fixed all the issues raised by the tests, if any.
- [x] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Update revert reason doc to indicate revert reason included in eth_estimateGas error.

## Issue fixed

fixes #580 

### For content changes

- [x] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

### CODE REVIEW

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Review by matkt — APPROVED** [review]
LGTM

**Comment by NicolasMassart** [comment]
@alexandratran I did not notice that but maybe you could add links in `/Reference/API-Methods/#eth_estimategas` targetting `/HowTo/Send-Transactions/Revert-Reason` with a text such as 
```
If the revert reason is enabled with the [`--revert-reason-enabled` option](link to /Reference/CLI/CLI-Syntax/#revert-reason-enabled),
[`eth_estimategas` error response](link to /Reference/API-Methods/#eth_estimategas)
will include the [revert reason](link to /HowTo/Send-Transactions/Revert-Reason)
```

Also updating `/Reference/CLI/CLI-Syntax/#revert-reason-enabled` to add the eth_estimategas method such as `Enables including the revert reason in the transaction receipt and [eth_estimategas error response](link to /Reference/API-Methods/#eth_estimategas)`

**Review by NicolasMassart — CHANGES_REQUESTED** [review]
@alexandratran I did not notice that for my first review pass but maybe you could add links in `/Reference/API-Methods/#eth_estimategas` targetting `/HowTo/Send-Transactions/Revert-Reason` with a text such as 
```
If the revert reason is enabled with the [`--revert-reason-enabled` option](link to /Reference/CLI/CLI-Syntax/#revert-reason-enabled),
[`eth_estimategas` error response](link to /Reference/API-Methods/#eth_estimategas)
will include the [revert reason](link to /HowTo/Send-Transactions/Revert-Reason)
```

Also updating `/Reference/CLI/CLI-Syntax/#revert-reason-enabled` to add the eth_estimategas method such as `Enables including the revert reason in the transaction receipt and [eth_estimategas error response](link to /Reference/API-Methods/#eth_estimategas)`

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Pull request merged**
