### PR TITLE
Removed postman api link from Besu API Methods

### PR DESCRIPTION
**Pull request by deveshXm**
This PR removes Besu JSON-RPC APIs documentation in Postman format from Besu API methods

## Issue fixed

fixes #[1286](https://github.com/hyperledger/besu-docs/issues/1286)

## Impacted parts

For content changes:

- [x] Documentation content
- [ ] Documentation page organization

For tool changes:

- [ ] Github Actions workflow
- [ ] Build and QA tools configuration (for example, lint rules or Vale style)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [ ] You've fixed any issues raised by the tests.
- [x] You've [previewed your changes on Read the Docs](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation)
  and added a [preview link](#preview).

## Preview

[preview](https://hyperledger-besu--{1286}.org.readthedocs.build/en/{1286}/stable/public-networks/reference/api/)

### CODE REVIEW

**Comment by macfarla** [comment]
https://github.com/hyperledger/besu-docs/actions/runs/4665743069/jobs/8270739251?pr=1302
the linter is checking for `multiple blank lines`
so to fix - just remove one blank line @deveshXm

**Review by siladu — CHANGES_REQUESTED** [review]
This appears to remove the entire postman section including the "Run in postman" button which didn't have any issues AFAICT, see this comment: https://github.com/hyperledger/besu-docs/issues/1286#issuecomment-1482158852

As per https://github.com/hyperledger/besu-docs/issues/1286#issuecomment-1504667945 I would like to discuss this further before we remove it please.

**Comment by alexandratran** [comment]
@deveshXm as per [this comment](https://github.com/hyperledger/besu-docs/issues/1286#issuecomment-1505862966), can you instead replace the dead link (https://api.besu.hyperledger.org/) in `global/postman.md` with [this working link](https://www.postman.com/hyperledger/workspace/hyperledger-besu/collection/11610746-f334929f-c8c3-43ed-bb73-69a6f0d728d8)?

**Comment by deveshXm** [comment]
> @deveshXm as per [this comment](https://github.com/hyperledger/besu-docs/issues/1286#issuecomment-1505862966), can you instead replace the dead link (https://api.besu.hyperledger.org/) in `global/postman.md` with [this working link](https://www.postman.com/hyperledger/workspace/hyperledger-besu/collection/11610746-f334929f-c8c3-43ed-bb73-69a6f0d728d8)?

Sure. I'll update it.

**Review by alexandratran — APPROVED** [review]

**Pull request merged**
