### PR TITLE
add besu-tessera high availability diagram

### LINKED ISSUE #312: Add diagram for high availability config for privacy
Like this one but update to match the style of our other diagrams: 

image

### PR DESCRIPTION
**Pull request by alexandratran**
## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [x] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [x] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [x] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [x] you fixed all the issues raised by the tests, if any.
- [x] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Add Besu-Tessera high availability diagram. Clarify using Besu in high availability (see comments on this PR).

## Issue fixed

fixes #312 

### For content changes

- [x] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

see https://hyperledger-besu--666.org.readthedocs.build/en/666/

### CODE REVIEW

**Review by atoulme — COMMENTED** [review]
Not sure Besu itself is highly available.

**Comment by NicolasMassart** [comment]
@atoulme 
> Not sure Besu itself is highly available.

This is a difficult subject indeed. Some parts are easy to make HA, some other have some constraints.

If you [use load balancers before redundant nodes](https://besu.hyperledger.org/en/stable/HowTo/Configure/Configure-HA/High-Availability/) (and each can be peered to the other) it should be HA.

_Node private keys (and then ID) are not concerned here  so they can be different on each node. For the P2P part, each node still appear as a specific node to the other peers._

For HTTP JSON-RPC, as we don't have any session state, you can switch from a node to the other without noticing it.

But it will require that you be careful about what protocol you use and if all the methods should work with Websockets because they maintain a steady connection once established and are then tied to a specific node, some may not provide the expected results with HTTP, for instance `admin_` or  `net_enode`, `net_peerCount`, `eth_syncing`, ...
@alexandratran this is maybe something to improve on [Besu RPC HA doc](https://besu.hyperledger.org/en/stable/HowTo/Configure/Configure-HA/High-Availability/).

Also config updates have to be done on both nodes though, but it's just sending the RPC request from behind the balanced or using a reverse proxy if the update is done using RPC, or keeping the config files in sync (it's OS/FS level here).

Even with JWT authentication it should be fine if authentication configs are in sync between the two nodes. Then you could ask a token on one and use it on the other.

## My suggestion for this PR

For this PR, add a sentence with a link to `/HowTo/Configure/Configure-HA/High-Availability.md` and clearly explain that there's some conditions for Besu HA.

Otherwise, the diagram seems fine for me.

**Review by bgravenorst — APPROVED** [review]
LGTM. You may want to run this through @joshuafernandes as well.

**Review by joshuafernandes — APPROVED** [review]
LGTM

**Pull request merged**
